### ISSUE TITLE
我想在模版里面访问window对象，可否在KEYWORDS数组中加入

### ISSUE THREAD

**Issue by mark422** [DavidKk/killt#1]
rt

**Comment by DavidKk** [comment]
所有模板引擎应道都避免这个防止注入的问题吧 如果确定要这样传入 可以在传入数据中传入
最后这个库也很久没更新 而且是本人旧项目用到的 star的人也不多 建议用更多人 star Issues 等 第三方库 例如 ejs handlebars 这样就不容易出现很多麻烦的问题没法解决

**Comment by mark422** [comment]
不是传入window哦，是这样的。比如我想在模版里面使用类似 parseFloat这种函数或者其他内置属性，因为这种不在过滤的KEYWORDS数组中，导致会被渲染为$data.parseFloat，我希望在KEYWORDS加入window，这样我就可以通过window.parseFloat等内置函数和属性了。

**Comment by DavidKk** [comment]
@mark422 模板引擎编译过程中 window, global 等全局变量尽量不能访问的, 才能保证执行编译的时候是一个与外部隔离的沙箱, 但是一些全局的方法 parseFloat, Math 等我要考虑一下是否和怎么加进里面, 你可以和其他第三方库一样的方式: 通过 helper 去实现这个需求先 ...

**Comment by mark422** [comment]
好的
